version: "3.3"

services:
    ntp:
      build: ./ServidorNTP_C
      ports:
        - "4444:4444"
    coordinador:
      build: ./coordinador_C
      ports:
        - "1234:1234"
      depends_on:
        - "broker"
    broker:
      build: ./broker_C
      ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
        - "3003:3003"
      depends_on:
        - "ntp"