version: "3.3"

services:
    ntp:
      build: ./ServidorNTP_C
      ports:
        - "4444:4444"
      networks:
        - some-net
    coordinador:
      build: ./coordinador_C
      ports:
        - "1234:1234"
      networks:
        - some-net
    broker:
      build: ./broker_C
      ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
        - "3003:3003"
      depends_on:
        - "ntp"
      networks:
        - some-net
      links: 
        - ntp
networks:
  some-net:
    driver: bridge