version: "3.3"

services:
    ntp:
      build: ./ServidorNTP_C
      ports:
        - "4444:4444"
    coordinador:
      build: ./coordinador_C
      ports:
        - "1234:1234"
      depends_on:
        - "broker1"
        - "broker2"
    broker1:
      build: ./broker_C
      ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
        - "3003:3003"
      depends_on:
        - "ntp"
      environment:
        pubPort: 3000
        subPort: 3001
        repPort: 3002
    broker2:
      build: ./broker_C
      ports:
        - "3004:3004"
        - "3005:3005"
        - "3006:3006"
        - "3007:3007"
      depends_on:
        - "ntp"
      environment:
        pubPort: 3004
        subPort: 3005
        repPort: 3006
    servidorhttp:
      build: ./ServidorHTTP_C
      ports:
        - "9123:9123"
      depends_on:
        - "broker1"
        - "broker2"
    